<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "<link href='./ff9_tw.css' rel='stylesheet' type='text/css' media='all'/>";
echo "</head><body>";
echo "<br><a name='ff9_101' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>１.&nbsp;车站<br /></td></tr>
<tr><th width=60>流程</th><td>偶遇-&gt;挣扎-&gt;改变</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table class=tw cellspacing=5><tr><td>“最近发生了很多事啊！”<br />在南大门前，那两个守卫士兵开始闲聊起来。从最近的火药情势谈到物美价廉的泡菜，两人又开始对刚才过去的背大袋子的家伙怀疑起来。<br />不过一切都太迟了，<span class=character>Steiner</span>和<span class=character>Dagger</span>早已坐上了前往的<span class=location>Treno</span>火车。<br /><br />“车长说马上就到终点站了。”列车上，<span class=character>Steiner</span>提醒公主说，然而她似乎却睡着了……回想着对女王陛下的种种传闻，<span class=character>Steiner</span>也很沮丧，不管怎么说，现在他的首要任务是保护好<span class=character>Dagger</span>的安全，把她护送回城堡。就在<span class=character>Steiner</span>思量这些的时候，列车到站了。</td></tr>
<tr><td>和乘务员道别之后，<span class=character>Dagger</span>站在月台上眺望着亚历山大国的领土，虽然还看不到城堡，但她已经很知足了。<br />“到家了……”<span class=character>Dagger</span>兴奋地说。<span class=character>Steiner</span>和她一起走进候车室，主动先去打听消息，剩下<span class=character>Dagger</span>一人。<br /><br />控制女主角和左边柜台前的服务员说话便能听到一声火车的汽笛声，接下来走出去便可发生剧情。不过在此之前最好把宝箱拿了，右边的莫古<span class=other>Nazna</span>还有送信的任务。<br /><br />门外，<span class=character>Dagger</span>再次见到了<span class=other>Tantalus</span>一伙……</td></tr>
<tr><td>跟着他们进入候车室，看到<span class=character>Steiner</span>正在和<span class=character>Cinna</span>、<span class=character>Marcus</span>争吵。<br />“你们这些混蛋，还想来绑架公主吗！”<span class=character>Steiner</span>主动挑起战事，对方也毫不逊色，交锋几句后，<span class=character>Dagger</span>打断他们：“<span class=character>Adelbert Steiner</span>！难道我就不能跟朋友说说话吗？”<br />“是、公——小、小姐……”面对一脸严肃的<span class=character>Dagger</span>，<span class=character>Steiner</span>完全没了辙。<br />“挨骂了。”<br />“够丢脸了。”<br /><span class=character>Cinna</span>和<span class=character>Marcus</span>在一旁冷嘲热讽道。</td></tr>
<tr><td>这时开往<span class=location>Treno</span>的火车到了，<span class=character>Cinna</span>送<span class=character>Marcus</span>上车，<span class=character>Dagger</span>见状决定和他一起去不夜城。在车上，<span class=character>Dagger</span>问起他去<span class=location>Treno</span>的原因。<br /><br />“去救我的哥哥。”<span class=character>Marcus</span>回答道。<br />“哥哥？”<span class=character>Dagger</span>对此疑惑不解。<br />“只有一个人我会称他为哥哥，那就是<span class=character>Blank</span>。”提起这个名字时<span class=character>Marcus</span>总会流露出一种很特殊的表情，“我们已经知道如何帮他解除石化了，那是一种叫做<span class=item>Supersoft</span>的药剂，它能解除所有的石化。”</td></tr>
<tr><td><span class=character>Marcus</span>接着告诉她<span class=character>Cinna</span>正是回秘密基地准备把这消息告诉其他人的。“现在该我问了。”<span class=character>Marcus</span>说。<br />向<span class=character>Dagger</span>打听了<span class=character>Zidane</span>的情况后，<span class=character>Dagger</span>正在为<span class=character>Blank</span>石化的事自责，突然间火车停下了。<br />列车员走出火车后不一会儿惊慌失措地跑进来说：“一个恶魔！一个尖帽子的恶魔！”<br /><br />一行人走出来后，发现列车员所说的尖帽子就是<span class=monster>Black Waltz No. 3</span>，不过现在他似乎神智不清而且身负重伤，只一心想把公主带回去。</td></tr>
<tr><td>BOSS战。<br />这家伙死到临头还要挣扎，不过不用担心，即使打不过他也不要紧，因为此战他是不会攻击<span class=character>Dagger</span>的，等<span class=character>Steiner</span>和<span class=character>Marcus</span>战斗不能了，他便会自己攻击自己。如此一来这场战斗我们稳操胜券。<br />从BOSS身上可以偷盗<span class=item>Lightning Staff</span>、<span class=item>Steepled Hat</span>、<span class=item>Flame Staff</span>几样物品。他有1292点HP。</td></tr>
<tr><td>结束后，<span class=character>Marcus</span>提及就是这群黑魔道士摧毁了<span class=location>Burmecia</span>，不过<span class=character>Dagger</span>似乎仍不愿意面对这个现实。<br />“我必须回城堡见我母亲……”<span class=character>Dagger</span>固执地想，“她会听我说的。”<br />在车厢里，<span class=character>Marcus</span>继续和她交谈着：“你变了。”<br />“我？你指我说的话？”<span class=character>Dagger</span>有点惊喜地说。<br />“不只这个。”<br />“也许吧，发生了这么多事……”<span class=character>Dagger</span>站起身来，“在经历过这么多的战斗后，我不再是小孩了！我们要找到<span class=item>Supersoft</span>去救<span class=character>Blank</span>，对吗？”<br />“即使我拒绝，你也会跟着来的吧？”<br />“当然！这是实在是令人兴奋！我一直都很想去看看<span class=location>Treno</span>非凡的建筑。我都等不及了！”<br />“其实，她没变多少。”在这辆缓缓行驶的列车上<span class=character>Marcus</span>这样想着。虽然行驶得不快，但它总会到达目的地的。<br />不管这条路有多长。</td></tr>
</table><font size=4><a href='#ff9_101'>返回2-1</a></font></div><br>";
echo "<br><a name='ff9_102' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>２. 不夜城<br /></td></tr>
<tr><th width=60>流程</th><td>岔路->夜->拍卖会</td></tr>
<tr><th>重要道具</th><td>Gemini<br />Taurus</td></tr>
</table><table class=tw cellspacing=5><tr><td>列车到站以后，下车便来到一个岔路口处。<br /><br />我们的目标是图中右边那条路通向的不夜城<span class=location>Treno</span><span class=ititle>，不过在此之前最好先走左边，回到曾经到过的——</span><span class=location>Village of Dali</span><span class=ititle>。</span><br /><br />它的宁静和谐的BGM还记得吗？</td></tr>
<tr><td>“从上次离开这儿到现在，这里给我的感觉还是那样……”<span class=character>Dagger</span>走进村子，若有感触地说。<br /><br />此次回来的目的主要是为了拿那个田里的宝箱——<span class=item>Elixir</span>。只有这一次机会，以后就不行了。完成之后便原路返回，从刚刚的岔路右边去<span class=location>Treno</span>。<br /><br />在那个岔路口，右边那条路中能遇到一架断桥，需要跳过去才行，下方有个宝箱，里面装有<span class=item>1610Gil</span>。不夜城外面的高原可以碰到第2个精灵<span class=monster>Ghost</span>。<br /><br />关于精灵事件请看专题<a href=./fairy.htm target=_blank>《精灵任务》</a>。</td></tr>
<tr><td>天色渐渐暗了下来，当我们来到<span class=location>Treno</span>时，已经夜深了。这里居住着许多贵族，因此彻夜灯火辉煌，非常热闹。<br />“住这的贵族并不是很多，夜长着呢。对贼来说，这可是个好地方。”<span class=character>Marcus</span>刚进大门就开始夸赞。<br />“就是你这样的人把这座城市变成了贫民窟！”<span class=character>Steiner</span>仿佛和他们有着永远也吵不完的架，然而就在俩人还在争论的时候，<span class=character>Dagger</span>一个人独自溜跑了。<br />“不，别再这样了……我服役的18年里从没处理过这么棘手的难题。这一切都是因为你和你的那些狐朋狗友……”<span class=character>Steiner</span>抱怨着说，当他再次转身时，发现<span class=character>Marcus</span>也没了踪影，“一个真正的骑士是不会被这样的小事影响的！我必须找到公主！”</td></tr>
<tr><td>最后控制<span class=character>Steiner</span>进门来到拍卖行找到<span class=character>Dagger</span>。<br />“公主！找到你太好了，我很担心你呢。”<span class=character>Steiner</span>如释重负。两人交谈几句后，决定先去找<span class=character>Marcus</span>，说不定他已经找到<span class=item>Supersoft</span>了……<br /><span class=character>Steiner</span>率先跑出拍卖会，<span class=character>Dagger</span>临走时又回头望望2楼。<br />“我以前曾经见过他……”<span class=character>Dagger</span>若有所思。其实眼尖的玩家应该看出来了，他就是<span class=character>Kuja</span>。<br /><br />做好准备之后就去宿屋吧，从<span class=location>Treno</span>门口走右边那条路过了一个场景便是，这个城市的东西还是挺丰富的，尤其是在拍卖会里能买到许多珍贵物品，以后更是能拿到一个<span class=character>Dark Matter</span>，不过需要到DISK3才能拿到……XD~</td></tr>
</table><font size=4><a href='#ff9_102'>返回2-2</a></font></div><br>";
echo "<br><a name='ff9_103' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>３. 家庭教师<br /></td></tr>
<tr><th width=60>流程</th><td>心事->老师->解药->秘道</td></tr>
<tr><th>重要道具</th><td>Supersoft</td></tr>
</table><table class=tw cellspacing=5><tr><td>在宿屋的下方看到<span class=character>Marcus</span>正等在那里。<br />“我们准备去拿<span class=item>Supersoft</span>。”他说。<br />“好！终于可以救<span class=character>Blank</span>了！什么时候行动？”<br />“现在就可以了。你也来的，对吧？准备好了吗？”<br />选择第一项“<span class=choose>准备好了</span>”。<br />在此不要理会<span class=character>Steiner</span>在你身后的絮叨，如果你和他对话了，那么就必须乖乖跟他回去……<br /><br />在地下来到一艘船的旁边，盗贼团首领<span class=character>Baku</span>正在那儿等着，几人见面又免不了要争吵一番，最后还是以<span class=character>Dagger</span>的“下定决心”收场。</td></tr>
<tr><td>拍卖会这边，<span class=character>Kuja</span>正和会长谈话。<br />“<span class=location>Burmecia</span>怎么样了？”会长问。<br />“还不错……”<span class=character>Kuja</span>换了个姿势，“如果没有见到那些垃圾和那个胖女人就更好了。”<br />“你跟着要去<span class=character>Cleyra</span>吗？”<br />“没错。我相信你也应该把他们交货了。”<br />“当然，我现在就去准备……”会长正转身要走，<span class=character>Kuja</span>拦住了他：“对了，你今天有见到一个漂亮的女孩吗？”<br />“漂亮的女孩？需要下令搜索吗？”<br />“那倒不必。我的小金丝雀……她迟早会自己飞到我的笼子里的。”<span class=character>Kuja</span>根本没在意会长疑惑的表情，伸开双手继续陶醉说，“我从没想过会在这个地方遇见你，这一定是命运。但是你还不能停下来……飞回你母亲那里去吧，我的小金丝雀。”</td></tr>
<tr><td>镜头转回<span class=character>Dagger</span>坐的小船上，<span class=character>Steiner</span>和她各自想着心事。<br /><br />“我究竟在做什么……我是在协助盗贼们犯罪吗……”<span class=character>Steiner</span>总是在自责，“不要担心这些无聊的犯罪活动，只要想着护送公主会城就够了。大概以后再也不会见到他了……他这个混蛋，把我和公主扯进他们的诡计……”<br /><br />“这是你的错，<span class=character>Zidane</span>。如果你不把我当小孩子……我就不需要为你的朋友去找<span class=item>Supersoft</span>了。”<span class=character>Dagger</span>这样想到，“为什么我要做这个……？因为<span class=character>Blank</span>救了我？是的，他救过我，他救过我的生命……最起码我要报答一下……但以前我从没有想过这种事……”</td></tr>
<tr><td>最后一行人来到一间地下室，这里其实就是合成店的后台。<br />“这么多箱子怎么才能找到<span class=item>Supersoft</span>啊。”<span class=character>Steiner</span>刚抱怨一句，<span class=character>Dagger</span>连忙让他放低声音，因为她发觉有人来了。<br />“唉，实在不相信居然在这么晚的时候把墨水用光了……”一个长鼻子学者慢慢踱下楼来，众人紧张地看着他。没想到<span class=character>Dagger</span>却主动跑上去：“我很想念你啊，<span class=character>Tot</span>博士。”<br />包括<span class=character>Steiner</span>在内大家都吃了一惊，原来<span class=character>Tot</span>以前是<span class=character>Dagger</span>的家庭教师，他是一个很有威望的学者。<br />可惜没有时间让他们叙旧了，吵闹声惊醒了商店老板。<br />“先走吧！我等会儿给你们<span class=item>Supersoft</span>。<span class=location>Treno</span>入口往左，一直走就见到一座塔。那是我的家,我到时会打开门等着你们来的。”<span class=character>Tot</span>这样说着，将我们送走，独自应付从楼梯上下来的老板。</td></tr>
<tr><td>“就是说，那个叫<span class=other>Tootsie</span>的会给我们<span class=item>Supersoft</span>？”回到宿屋后，<span class=character>Baku</span>忍不住问。<br />“是<span class=character>Tot</span>……”<span class=character>Marcus</span>更正道。<br />“太好啦！”他也不管有没有人回答就开始兴奋起来，“不过，真不敢相信我们<span class=other>Tantalus</span>会欠一个老人的情啊。那我们就要好好照顾公主了。”<br />“还有呢？”<br />“如果不是公主他是不会给我们<span class=item>Supersoft</span>。这就是关键，公主。我们需要你带<span class=character>Marcus</span>去见<span class=other>Toot</span>。”<br />“……是<span class=character>Tot</span>。”<span class=character>Marcus</span>再次更正。<br />“我正要去。”<span class=character>Dagger</span>回答说。<br />“那，出发前休息一下吧。”<span class=character>Baku</span>最后说道，“我想<span class=other>Ted</span>大概需要时间准备一下。”<br />“……是<span class=character>Tot</span>……”<span class=character>Marcus</span>无奈了。</td></tr>
<tr><td>按<span class=character>Tot</span>所说，我们来到那个塔楼上，他正在那儿等我们。<br />“公主！谢谢来访，欢迎来到寒舍！”<span class=character>Tot</span>很热情地说。<br />“这是你家？”<span class=character>Dagger</span>不可思议地问。<br />“离开亚历山大后我找人支持我的研究很久，后来终于在<span class=location>Treno</span>找到一家，”<span class=character>Tot</span>仔细打量面前这位熟悉而又陌生的面孔，“你已经长得婷婷玉立了，真高兴再见到你啊。”<br />一行人继续互道别情，<span class=character>Marcus</span>进来后问了一句<span class=item>Supersoft</span>在哪直接就把地上的箱子打开了。<br />“没礼貌的家伙？快谢谢博士吧！”<span class=character>Steiner</span>忍不住又向他发起“攻击”。<br />“没关系，<span class=character>Steiner</span>大人。”<span class=character>Tot</span>表示过不介意后，<span class=character>Dagger</span>开始对旁边的巨大的星仪来了兴趣。<br />“<span class=character>Tot</span>博士，这是<span class=other>Gaia</span>吗？”她问。<br />“是的，是我们行星的模型，<span class=other>Gaia</span>。”<span class=character>Tot</span>回答。<br />“我记起你的讲课了。”<br />“你还记得我这个老糊涂以前的事啊……”</td></tr>
<tr><td>回忆结束，<span class=character>Dagger</span>和<span class=character>Tot</span>站在星仪的前面。<br />“有多久了？8年了吗？”<span class=character>Dagger</span>问道。<br />“时间过得真快啊。”<span class=character>Tot</span>感叹，“但我还没变，我还在找这些东西作研究。”<br />“你在哪里找到这个星仪的？”<br />“这是个古董。如你所见，已经是坏掉的了，但我用来做瞭望台。”<span class=character>Tot</span>笑了笑，“很讽刺吧？从星仪里看天空。”<br />“这确实……”<span class=character>Dagger</span>似乎有话要说，但又停住了。<br />“公主，我不是想多管闲事，但……我是站在你那边的，现在是，以后也是。如果有需要，请跟我说。”<br />“<span class=character>Tot</span>博士……”<span class=character>Dagger</span>感激地望着他。</td></tr>
<tr><td>镜头再次回到一行人身上，<span class=character>Tot</span>站在一个通道入口前。<br />“我明白了，女王的军队已经很强大了……”<span class=character>Tot</span>说，“好，虽然这可能有危险，但我还是希望你回去<span class=character>Alexandria</span>看看。”他打开那个入口的盖子，“我有一个重建的古老传送装置，以防万一。请往这边。”<br />“啊！我们终于可以回<span class=location>Alexandria</span>了！”<span class=character>Steiner</span>叫道。<br />“我跟你们一起去。”<span class=character>Marcus</span>说了一句。<br />“什么？为什么！”<span class=character>Steiner</span>显然很不高兴和他同行。<br />“我从<span class=location>Alexandria</span>可以更快到<span class=character>Blank</span>那里。”<br />“对啊，跟我们一起走吧，<span class=character>Marcus</span>。”如往常一样，<span class=character>Dagger</span>最后来打圆场，“好吗，<span class=character>Steiner</span>？”<br />“呃……”显然他只有默许了。<br />“让我们去救<span class=character>Blank</span>吧！”<span class=character>Dagger</span>欢快地说，“还有把母后恢复到和以前一样！”<br />……她还是没有长大。<br /><br />在跟着老师进地道之前，可以尝试先出门一下，有一个隐藏ＡＴＥ。</td></tr>
</table><font size=4><a href='#ff9_103'>返回2-3</a></font></div><br>";
echo "<br><a name='ff9_104' />
<div align='center' id='ff9tw'><table cellpadding=0 cellspacing=0 class=intro><tr><td colspan=2 class=ititle>４．虫道<br /></td></tr>
<tr><th width=60>流程</th><td>初入虫道->寻找机关-><br />地底怪兽->落入陷阱</td></tr>
<tr><th>重要道具</th><td>-</td></tr>
</table><table cellspacing=5 class='tw'><tr><td>一行人沿楼梯下动一个坑道中。画面上浮现一排大字--<span class=location>Gargan Roo</span>。<span class=character>Tot</span>首先开口说道：“这里是<span class=location>Gargan Roo</span>，连接<span class=location>Treno</span>和<span class=location>Alexandria</span>的一条古老地道。”<br /><span class=character>Marcus</span>问了一句：“为什么这东西会建在塔底的？” <br /><span class=character>Tot</span>回答说：“实际上，<span class=location>Gargan Roo</span>在飞空艇发明的很久之前就已经使用了！”<br /><span class=character>Dagger</span>有点疑惑：“但这里看起来很新啊。” <br />“是我叫主教先生管理好这里的。在这里重建好之后我都还没有用过，我们首先要找到通道连接开关，把里面的<span class=monster>gargant</span>叫出来。”<span class=character>Tot</span>开始沉思起来，“嗯……开关在哪里呢？”</td></tr>
<tr><td>提示：<br />1.这里可以碰到的怪物为<a href=./mon_c.htm target=_blank>Crawler</a>和<a href=./mon_d.htm target=_blank>Dragonfly</a>，没有什么特殊能力，偷不到什么好东西，随便杀之。<br />2.如果之前在路行鸟森林狂挖过宝拿到了<span class=item>Protect Ring</span>，这里可以给<span class=character>Dagger</span>装备上，以获得<span class=magic>消费MP半减</span>的能力。这样可以提前在这里试着拿召唤兽过下瘾。马上召唤兽就要被抽走了，现在不耍，再想耍就要拖后好多了。</td></tr>
<tr><td>“那么，我们先要找到开关。” <span class=character>Steiner</span>看看<span class=character>Tot</span>似乎暂时想不起来，提议说，“公主，我们快找吧！”。 <br />看看<span class=character>Tot</span>还在那里抱着脑袋死想，估计是没法指望他想起来了，我们只好动身自己去找了。下面的莫古猪可以存档，还有一封信是要交给他的。这里出没的怪物是<span class=monster>Crawler</span>和<span class=monster>Dragonfly </span>。<br /><br />先往左下角走过去。一进去的右下一点就有一个箱子，得到<span class=item>Chain Plate </span>。之后走到左上角，在箱子里的是<span class=item>Phoenix Down</span>。旁边有个机关，扳动它后沿原路返回。</td></tr>
<tr><td>接着走右下的路，进去有一直往右上走到顶。<br /><span class=character>Tot</span>也跟了过来：“啊，就是这个了 ！这就是我们说的<span class=monster>gargant</span>了！” <br /><span class=character>Dagger</span>问道：“什么意思？”<br />“<span class=location>Gargan Roo</span>的<span class=location>Treno</span>站就像个圆环。”<span class=character>Tot</span>解释着，“拉下那个杆，<span class=monster>gargant</span>就不停的围着站转圈，还是你自己看吧。公主，你能拉一下那里的杆吗？” <br /><span class=character>Dagger</span>上前把那个机关拉下，一声虫叫传了出来。<br /><span class=character>Dagger</span>盯着隧道深处：“什么东西！？”<br />只见一只巨大的像蜘蛛一样的生物，倒挂着走过，身上挂着一个有座位的篮子，就好像观览车。<br /><span class=character>Dagger</span>问道：“那是什么！？”<br />“这就是<span class=monster>gargant</span>，驱动这车子的巨虫。现在我们要叫停它。” 说完，<span class=character>Tot</span>转身跑出了画面。</td></tr>
<tr><td>跟着<span class=character>Tot</span>跑过去，发现这个健忘的家伙又忘了下个开关在哪了。哎，不管他了，直接走到画面左下角，发现一个开关，刚要扳下来。<span class=character>Tot</span>就跑了过来：“就是这个！一拉这条杆，<span class=monster>gargant</span>就会停下来的了。”<br /><span class=character>Dagger</span>拉了一下。从天顶上降下了一个装着花草的篮子，<span class=monster>gargant</span>停在那里吃了起来。<br /><span class=character>Tot</span>说道：“大家快上。它吃完就走的了。” <br /><span class=character>Dagger</span>担忧道：“你肯定它不会一直转圈吗？”<br /><span class=character>Tot</span>回答说：“不会的。我会倒过开关顺序让<span class=monster>gargant</span>离开的。”，接着他转向<span class=character>Tot</span><span class=character>Steiner</span>：“请照顾好公主，<span class=character>Steiner</span>大人。公主很聪明，但她还是太年轻，太天真了。我真担心她的安全。危急关头请果断点，好好保护公主。”<br /><span class=character>Steiner</span>答道：“……我会紧记你的说话的。”</td></tr>
<tr><td>一行人离开后，<span class=character>Tot</span>跑去倒转了开关。<br />镜头回到<span class=character>Dagger</span>这边。<br />“我们可以回到<span class=location>Alexandria</span>了……”<span class=character>Dagger</span>说着，“我想知道还要走多久？”<br /><span class=character>Steiner</span>看着头上的巨虫赞叹道：“<span class=character>Tot</span>博士真是个了不起的人啊！”<br />这时，巨虫停了下来，并向后退去。<br />“发生了什么？它好象很紧张。”<span class=character>Dagger</span>向前方看去，“！！！”发现了什么的她跳下座位跑进了隧道，<span class=character>Steiner</span>和<span class=character>Marcus</span>也紧跟了上来。<br />只见一只巨大的蛇状怪物盘踞在隧道中。<br />“这就是原因了！”<span class=character>Dagger</span>说道。</td></tr>
<tr><td><span class=choose>BOSS战：</span>对战怪物为<a href=./mon_r.htm target=_blank>Ralvurahva</a>。<br />这个怪物身上可以偷到<span class=item>Bone Wrist</span>和<span class=item>Mythril Fork</span>。很简单的BOSS,注意点解毒就能轻松ＫＯ。如果实在担心不好打的话，推荐个简单方法，一开场使用道具砸给BOSS一个<span class=item>Tent</span>。看BOSS中了一堆状态的话再开始慢慢或杀或偷吧。这时的BOSS攻击基本是打不中我方成员的，连解毒都省了。</td></tr>
<tr><td>ＢＯＳＳ战后，一行人来到了一个站台。<br /><span class=character>Steiner</span>看着周围：“我从来不知道<span class=location>Alexandria</span>还有这样一个地方。” <br /><span class=character>Marcus</span>有些怀疑：“这真的是<span class=location>Alexandria</span>？”<br /><span class=character>Steiner</span>答道：“当然，这肯定是！”<br /><span class=character>Marcus</span>继续问着：“那我们怎么从这出去？”<br />“Hmm。。。没错。。。”<span class=character>Steiner</span>迟疑了一下就向后跑起来，“这边！公主，咱们快点。”<br />“等等，<span class=character>Steiner</span>！我知道这个地方！”<span class=character>Dagger</span>叫住了<span class=character>Steiner</span>，“我的祖先为了关押侵略的敌人而修建了这个地方。”<br />“公主！我们可以以后再听你的故事！”<span class=character>Steiner</span>插嘴说：“这陈腐的空气对我们太不好了！”<br /><span class=character>Marcus</span>跟着说道：“还有我们还要去救<span class=character>Blank</span>！”<br />“对。我们得抓紧时间。”<span class=character>Dagger</span>赞同着。</td></tr>
<tr><td>一行人向里走去。突然，他们面前出现一个巨大的铁栏，挡住了他们的去路。<br /><span class=character>Steiner</span>转过头恶狠狠的盯着<span class=character>Marcus</span>：“你！你在搞什么鬼！？”<br />“我什么也没干！别指着我。”<span class=character>Marcus</span>解释着，“你不相信我吗！？”<br />就在这时，另一个铁栏出现，堵住了他们的退路。2个小丑<span class=character>Zorn</span>和<span class=character>Thorn</span>出现在两边的高台上。<br /><span class=character>Zorn</span>说道：“抓住他们了！”<br /><span class=character>Thorn</span>也附和着：“他们被抓住了！”<br /><span class=character>Steiner</span>一看是两个小丑，命令道：“<span class=character>Zorn</span>! <span class=character>Thorn</span>！我是<span class=character>Steiner</span>，Pluto的骑士队长！我回来了！立刻让我们出去！”<br /><span class=character>Thorn</span>和<span class=character>Zorn</span>一脸虚假的惋惜：“真可惜，你们都被捕了。不管你愿不愿意，我们都要带你去见<span class=character>Brahne</span>女王。”他们不慌不忙的说着，“‘抓住<span class=character>Garnet</span>公主’，这就是<span class=character>Brahne</span>女王的命令！” <br />“什么？！”，“胡说！！”，“到底发生什么事了！？”<span class=character>Dagger</span>一行人都吃了一惊。<br />画面转黑。</td></tr>
</table><font size=4><a href='#ff9_104'>返回2-4</a></font></div><br>";
echo "<br><a name='ff9_105' />
<div id=ff9tw align=center><table class=intro cellspacing=0 cellpadding=0><tr><td class=ititle colspan=2>５．克雷拉<br /></td></tr>
<tr><th width=60>流程</th><td>战后休整->追赶->突入克雷拉</td></tr>
<tr><th>重要道具</th><td>－</td></tr>
</table><table class=tw cellspacing=5><tr><td>画面回到<span class=location>Burmecia</span>，<span class=character>Zidane</span>一行人惨败的地方，天空的雨依然下个不停。<br />“你们还能站起来吗？<span class=character>Freya</span>？<span class=character>Vivi</span>？”<span class=character>Zidane</span>首先站了起来。<br />“恩，还行”<span class=character>Freya</span>似乎还有点虚弱。<br />“我也没事，”<span class=character>Vivi</span>答道。<br />“接下来我们怎么办？听他们说要去<span class=location>Cleyra</span>。”<br />“别无选择，我们也去<span class=location>Cleyra</span>，<span class=character>Vivi</span>你呢？”<br />“我跟你们去，我想要知道更多关于黑魔导士的事情”<br />“<span class=location>Cleyra</span>？听上去似乎很好吃，我也跟你们去，”<span class=character>Quina</span>依然到哪都忘不了吃。<br />“据说<span class=location>Cleyra</span>坐落在风暴之中，不知道我们是否能到达那里。”<span class=character>Freya</span>有一些担心。“没看到<span class=location>Dagger</span>，看来她不在<span class=location>Burmecia</span>。”<span class=character>Zidane</span>想着。<br />一行人跑出画面。</td></tr>
<tr><td>离开青之王都往西南方向跑，可以看到一片沙漠中有一个龙卷沙暴，这就是<span class=location>Cleyra</span>。<br />“沙暴在不断减弱，”<span class=character>Freya</span>很是担心，“我的天哪，我们要尽快赶到<span class=location>Cleyra</span>。”<br />“对，要快点，”<span class=character>Quina</span>句句都能说到吃，“要快点找到美味的食物。”<br />一行人穿过暴风圈向<span class=location>Cleyra</span>跑去。<br /><br />远远的一棵巨大的古树矗立在暴风眼中间。狂躁的风暴似乎在保护古树，如围墙一般环绕着古树却并不侵袭古树。</td></tr>
<tr><td>一路往前走，来到第一道门前，先往右上走点有个机关，打开后进门。<br />进门右边就有一个箱子，打开后获得<span class=item>Phoenix Down</span>。<br />继续向上到一个中间长树的场景。此处有两个箱子都藏的比较隐蔽，打开后分别获得<span class=item>Magician Shoes</span>和<span class=item>Ice Staff</span>。<br />继续往右，顺着沙路往上，路过一个场景，进来左下一点可以拿到<span class=item>Ether</span>。之后走到右下一点，这里地上有个小洞，选择“<b>Put hand into hote</b>”把手伸进去拉开机关，然后返回。来到外面沿树藤爬上去。<br /><br />提示：1.这里随即遇敌可碰到的怪物有：<a href=./mon_s.htm target=_blank>Sand Golem</a>，<a href=./mon_d.htm target=_blank>Dragonfly</a>，<a href=./mon_g.htm target=_blank>Carrion Worm</a>和<a href=./mon_z.htm target=_blank>Zuu</a>。其中<span class=monster>Sand Golem</span>和<span class=monster>Zuu</span>在攻略时需要稍加注意。前者只有攻击其胸前那个类似红宝石的中枢才有效果，而攻击其沙子身躯则会被中枢无限复活。而后者则会在受到攻击后吞食我方成员，最好以强力攻击迅速消灭之，有想吃这家伙学青魔法的最好先尝试一次当前最大攻击速杀之，然后控制好攻击血量在一到两次之内将怪物的血降到3/4以下，否则会比较危险。<br />2.这里<span class=character>Quina</span>可以吃到青魔法<span class=magic>Matra Magic</span>，<span class=magic>White Wind</span>和<span class=magic>Auto-Life</span>。<br />具体细节请查阅专题<a href=./ff9_magic2.php target=_blank>《青魔法》</a></b></td></tr>
<tr><td>来到一个新场景，这里上面的树干上还有一个宝箱，不过暂时无法获取，过一会回来才能拿到，先往右边进洞。<br />进洞后左下流沙处可以拿到<span class=item>Needle Fork</span>，继续往上走，右边可以拿到<span class=item>Tent</span>，而左边的莫古<span class=other>Monev</span>则有个送信的事件，同时可以在这里消耗<span class=item>Tent</span>做一下恢复。之后依然向上攀登。</td></tr>
<tr><td>来到一个岔路，这里竖着一块牌子指着右边，上面写着<span class=location>Cleyra</span>的字样。<br />不过我们先走右边，可以获得<span class=item>Flame Staff</span>，之后返回再走左边的路。<br />到达一个吊桥场景，这里没什么东西，继续往右走。</td></tr>
<tr><td>来到一个洞穴场景。这里有3个宝箱，分别可以获得<span class=item>Mythril Vest</span>，<span class=item>Desert Boots</span>和<span class=item>Remedy</span>，拿完后从场景中间上去。<br />刚刚进来的地上可以拿到<span class=item>Mythril Gloves</span>，接着继续向前，尽头有一个机关，打开后返回洞穴场景，从左边的路上去。<br />进来是一岔路，右边的地上可以获得<span class=item>Potion</span>，拿到后从右边的小路上去，尽头可以获得<span class=item>Elixir</span>，然后返回岔路，从左边向上前进。<br />来到一个很多沙陷阱的房间。这里有两个宝箱，分别装着<span class=item>Hi-Potion</span>和<span class=item>900Gil</span>。<br />注意：走偏掉入沙陷阱的话就快速点击确定按钮，可以慢慢爬出来跳离陷阱。如果点慢了会沉入陷阱而强制遇敌，战斗胜利后自动跳离陷阱。<br />如果觉得棘手大可不必着急拿取那两个宝箱，以后会有更简单的机会获得。<br />一路从右边走到尽头，可以看到一个梯子，在获取梯子后面的<span class=item>Gysahl Greens</span>后便可以从梯子上去了。</td></tr>
</table><font size=4><a href='#ff9_105'>返回2-5</a></font></div><br>";



//echo "<br><a name='ff9_101' />
//<font size=4><a href='#ff9_101'>返回2-1</a></font></div><br>";
echo "</body></html>";
?>
