<?php
echo "<html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />";
echo "<link href='./ff9.css' rel='stylesheet' type='text/css' media='all'/>";
echo "</head><body>";
echo "<center><font color=red size=5>最终幻想9攻略</font><br>";
echo "<table width=80% border=0 cellpading=0 cellspacing=0>";
echo "<tr><td align=center><br><font size=4><a href='./ff9_skill.php' target=_blank>技能列表</a></font></td></tr>";
echo "<tr><td align=center><br><font size=4><a href='./ff9_magic1.php' target=_blank>黑、白魔法列表</a></font></td></tr>";
echo "<tr><td align=center><br><font size=4><a href='./ff9_magic2.php' target=_blank>青魔法列表</a></font></td></tr>";
echo "<tr><td align=center><br><font size=4><a href='./ff9_magic3.php' target=_blank>召唤魔法列表</a></font></td></tr>";
echo "<tr><td align=center><br><strong>个人特技列表</strong><br><br><font size=4>
<a href='./ff9_special_jitan.php' target=_blank>吉坦特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_xiaodao.php' target=_blank>小刀特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_vivi.php' target=_blank>比比特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_stanna.php' target=_blank>斯坦纳特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_freya.php' target=_blank>弗蕾雅特技</a>&nbsp;&nbsp;&nbsp;&nbsp;</td></tr><tr><td align=center><br><br><font size=4>
<a href='./ff9_special_ama.php' target=_blank>阿曼达特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_eiko.php' target=_blank>艾可特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href='./ff9_special_chan.php' target=_blank>阿馋特技</a>&nbsp;&nbsp;&nbsp;&nbsp;
</font></td></tr>";
echo "<tr><td align=center><br><table width=80% cellpadding=3 cellspacing=0 border=1>";
echo "<tr><td align=center colspan=6><strong><font size=4>DISC1攻略</font></strong></td></tr>";
echo "<tr><td><a href='./ff9_01.php#ff9_001' target=_blank>(1)序章</a></td>";
echo "<td><a href='./ff9_01.php#ff9_002' target=_blank>(2)亚历山大广场</a></td>";
echo "<td><a href='./ff9_01.php#ff9_003' target=_blank>(3)剧场艇演出</a></td>";
echo "<td><a href='./ff9_01.php#ff9_004' target=_blank>(4)诱拐计划</a></td>";
echo "<td><a href='./ff9_01.php#ff9_005' target=_blank>(5)逃离</a></td>";
echo "<td><a href='./ff9_01.php#ff9_006' target=_blank>(6)魔之森</a></td></tr>";
echo "<tr><td><a href='./ff9_01.php#ff9_007' target=_blank>(7)森林逃亡</a></td>";
echo "<td><a href='./ff9_01.php#ff9_008' target=_blank>(8)雾之大陆</a></td>";
echo "<td><a href='./ff9_01.php#ff9_009' target=_blank>(9)冰之洞窟</a></td>";
echo "<td><a href='./ff9_01.php#ff9_010' target=_blank>(10)达利村</a></td>";
echo "<td><a href='./ff9_01.php#ff9_011' target=_blank>(11)隐藏在地下的秘密</a></td>";
echo "<td><a href='./ff9_01.php#ff9_012' target=_blank>(12)空中激战 </a></td></tr>";
echo "<tr><td><a href='./ff9_01.php#ff9_013' target=_blank>(13)巨大城</a></td>";
echo "<td><a href='./ff9_01.php#ff9_014' target=_blank>(14)狩猎大会</a></td>";
echo "<td><a href='./ff9_01.php#ff9_015' target=_blank>(15)新的伙伴</a></td>";
echo "<td><a href='./ff9_01.php#ff9_016' target=_blank>(16)陷落的通道</a></td>";
echo "<td><a href='./ff9_01.php#ff9_017' target=_blank>(17)分道扬镳</a></td>";
echo "<td><a href='./ff9_01.php#ff9_018' target=_blank>(18)青之王都</a></td></tr>";
echo "</table></td></tr>";
echo "<tr><td align=center><br><table width=80% cellpadding=3 cellspacing=0 border=1>";
echo "<tr><td align=center colspan=6><strong><font size=4>DISC2攻略</font></strong></td></tr>";
echo "<tr><td><a href='./ff9_02.php#ff9_101' target=_blank>(1)车站</a></td>";
echo "<td><a href='./ff9_02.php#ff9_102' target=_blank>(2)不夜城</a></td>";
echo "<td><a href='./ff9_02.php#ff9_103' target=_blank>(3)家庭教师</a></td>";
echo "<td><a href='./ff9_02.php#ff9_104' target=_blank>(4)虫道</a></td>";
echo "<td><a href='./ff9_02.php#ff9_105' target=_blank>(5)克雷拉</a></td>";
echo "<td><a href='./ff9_02.php#ff9_106' target=_blank>(6)克雷拉街道</a></td></tr>";
echo "<tr><td><a href='./ff9_02.php#ff9_107' target=_blank>(7)克雷拉崩坏</a></td>";
echo "<td><a href='./ff9_02.php#ff9_108' target=_blank>(8)亚历山大的救援</a></td>";
echo "<td><a href='./ff9_02.php#ff9_109' target=_blank>(9)逃出亚历山大</a></td>";
echo "<td><a href='./ff9_02.php#ff9_110' target=_blank>(10)女王的杀手</a></td>";
echo "<td><a href='./ff9_02.php#ff9_111' target=_blank>(11)雷神的考验</a></td>";
echo "<td><a href='./ff9_02.php#ff9_112' target=_blank>(12)被摧毁的巨大城</a></td></tr>";
echo "<tr><td><a href='./ff9_02.php#ff9_113' target=_blank>(13)地下的隐藏通道</a></td>";
echo "<td><a href='./ff9_02.php#ff9_114' target=_blank>(14)外侧大陆的矮人村</a></td>";
echo "<td><a href='./ff9_02.php#ff9_115' target=_blank>(15)黑魔导士之村</a></td>";
echo "<td><a href='./ff9_02.php#ff9_116' target=_blank>(16)矮人村的婚礼</a></td>";
echo "<td><a href='./ff9_02.php#ff9_117' target=_blank>(17)又一个召唤士</a></td>";
echo "<td><a href='./ff9_02.php#ff9_118' target=_blank>(18召唤士之村)</a></td></tr>";
echo "<tr><td><a href='./ff9_02.php#ff9_119' target=_blank>(19)艾可的决定</a></td>";
echo "<td><a href='./ff9_02.php#ff9_120' target=_blank>(20)Iifa Tree</a></td>";
echo "<td><a href='./ff9_02.php#ff9_121' target=_blank>(21)在Madain Sari的战斗</a></td>";
echo "<td><a href='./ff9_02.php#ff9_122' target=_blank>(22)在Iifa Tree的战斗</a></td>";
echo "<td></td><td></td></tr>";
echo "</table></td></tr>";

echo "<tr><td align=center><br><table width=80% cellpadding=3 cellspacing=0 border=1>";
echo "<tr><td align=center colspan=6><strong><font size=4>DISC3攻略</font></strong></td></tr>";
echo "<tr><td><a href='./ff9_03.php#ff9_201' target=_blank>(1)回到Alexandria城</a></td>";
echo "<td><a href='./ff9_03.php#ff9_202' target=_blank>(2)Treno的卡片之旅</a></td>";
echo "<td><a href='./ff9_03.php#ff9_203' target=_blank>(3)在Alexandria的战斗</a></td>";
echo "<td><a href='./ff9_03.php#ff9_204' target=_blank>(4)Lindblum城</a></td>";
echo "<td><a href='./ff9_03.php#ff9_205' target=_blank>(5)黑魔法师之村</a></td>";
echo "<td><a href='./ff9_03.php#ff9_206' target=_blank>(6)沙漠</a></td></tr>";
echo "<tr><td><a href='./ff9_03.php#ff9_207' target=_blank>(7)Forgotten Continent</a></td>";
echo "<td><a href='./ff9_03.php#ff9_208' target=_blank>(8)Oeilvert</a></td>";
echo "<td><a href='./ff9_03.php#ff9_209' target=_blank>(9)Desert Palace</a></td>";
echo "<td><a href='./ff9_03.php#ff9_210' target=_blank>(10)Esto Gaza</a></td>";
echo "<td><a href='./ff9_03.php#ff9_211' target=_blank>(11)Mount Gulug</a></td>";
echo "<td><a href='./ff9_03.php#ff9_212' target=_blank>(12)飞空艇</a></td></tr>";
echo "<tr><td><a href='./ff9_03.php#ff9_213' target=_blank>(13)Alexandria</a></td>";
echo "<td><a href='./ff9_03.php#ff9_214' target=_blank>(14)Daguerreo</a></td>";
echo "<td><a href='./ff9_03.php#ff9_215' target=_blank>(15)Ipsen's Castle</a></td>";
echo "<td><a href='./ff9_03.php#ff9_216' target=_blank>(16)四大守护</a></td>";
echo "<td><a href='./ff9_03.php#ff9_217' target=_blank>(17)Terra</a></td>";
echo "<td><a href='./ff9_03.php#ff9_218' target=_blank>(18)Bran Bal</a></td></tr>";
echo "<tr><td><a href='./ff9_03.php#ff9_219' target=_blank>(19)Pandemonium</a></td>";
echo "<td></td><td></td><td></td><td></td><td></td></tr>";
echo "</table></td></tr>";

echo "<tr><td align=center><br><font size=4><a href='./ff9_03.php' target=_blank>攻略DISC3</a></font></td></tr>";
echo "<tr><td align=center><br><font size=4><a href='./ff9_04.php' target=_blank>攻略DISC4</a></font></td></tr>";

echo "</table></center></body></html>";
?>
